# When a pull request is merged for a branch with prefix “release/****” and a 
# version label to the main branch, trigger a github workflow to update the a 
# changelog with the current versions changes

name: Test Merge PR to Release
on:
  pull_request:
    branches:
      - 'testing'
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/heads/testing')
    steps:
    - name: Setup Checkout 
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1  
      with:
        node_version: 12
    - run:
        echo '${{github.event.pull_request.labels}}'
    - name: Install Changelog Generator
      run: 
        npm install -g standard-version
    - name: Set Github Configuration
      run: |
        git add .
        git config --global user.email "${{github.actor}}@users.noreply.github.com"
        git config --global user.name "${{github.actor}}"
    - name: Generate Updated Changelog
      run:
        standard-version cli.js
    - name: Commit Updated Changlog File
      run: |
        git push origin testing-workflows