name: Publish

on:
  push:
    branches:
    - testing-workflows

jobs:
  publish:
    name: Publish or Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install Dependencies
        run: yarn install
      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
