# When a pull request is merged for a branch with prefix “release/****” and a 
# version label to the main branch, trigger a github workflow to update the a 
# changelog with the current versions changes

name: 'Objective 1: Update Changelog on Merged PR Releases'
on:
  pull_request:
    branches:
      - 'testing-workflows'
    types: [closed, open]
    # paths-ignore:
    #   - '.changeset/**'
    #   - '**/CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.ref, 'testing') && contains( github.event.pull_request.labels.*.name, 'Version')
    steps:
    - name: Setup Checkout 
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1  
      with:  
        node_version: 12
    - name: Install Packages
      run:
        yarn
    - name: Set Github Configuration
      run: |
        git add .
        git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
        git config --global user.name "${{ secrets.GITHUB_ACTOR }}"

    - name: PR to Changesets
      run: |
        echo 'owner ${OWNER} repo ${REPO} pullRequestNumber ${PR_NUMBER} output ".changeset/${OWNER}-${REPO}-${PR_NUMBER}.md'
        npx pr-to-changesets --config .github/pr-to-changesets.json --owner ${OWNER} --repo ${REPO} --pullRequestNumber ${PR_NUMBER} --output ".changeset/${OWNER}-${REPO}-${PR_NUMBER}.md"
      env:
        OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
        REPO: ${{ github.event.pull_request.head.repo.name }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Git push
      run: |
        git add .changeset
        git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
        git config --global user.name "${{ secrets.GITHUB_ACTOR }}"
        git commit -m "CI(changeset): add changeset for PR #${PR_NUMBER}"
        git push origin-with-token testing-workflows
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        PR_NUMBER: ${{ github.event.pull_request.number }}
    # - name: Set Github Configuration
    #   run: |
    #     git add .
    #     git config --global user.email "${{github.actor}}@users.noreply.github.com"
    #     git config --global user.name "${{github.actor}}"
    # - name: Generate Updated Changelog
    #   run:
    #     npm run release -- --no-verify
    # - name: Commit Updated Changlog File
    #   run: |
    #     git push --follow-tags origin testing-workflows