name: Tags Test

on:
  push:
    branches:
      - 'testing-workflows'
    tags:
      - '**'

jobs:
  tagspush:
    name: Push on Tag Reference 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Create Tags Action
        run: echo "This is testing the tags action"
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
       