name: Testng PR-to-Changesets 2

on:
  push:
    branches:
      - merger-test
    # types: [closed]
    # paths-ignore:
    #   - '.changeset/**'
    #   - '**/CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: set remote url
        run: |
          git add .
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git config --global user.name "${{github.actor}}"
      - name: setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: PR to Changesets
        env:
          OWNER: ${{github.actor}}
          REPO: ${{github.actor}}
          PR_NUMBER: ${{github.actor}}
          GITHUB_TOKEN: ${{github.actor}}
        run:
          echo 'owner ${{github.actor}} repo ${{github.actor}} pullRequestNumber ${PR_NUMBER} output .changeset/${OWNER}-${REPO}-${{github.actor}}.md'
        
      # - name: Git push
      #   run: |
      #     git add .changeset
      #     git commit -m "CI(changeset): add changeset for PR #${PR_NUMBER}"
      #     git push origin-with-token testing-webflows
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PR_NUMBER: ${{ github.event.pull_request.number }}
